services:
  1min-relay:
    image: ghcr.io/kokofixcomputers/1min_relay:main
    container_name: 1min-relay-container
    ports:
      - "5001:5001"
    environment:
      # Use comma-separated string for ONE_MIN_AVAILABLE_MODELS Default: "mistral-nemo", "gpt-4o", "deepseek-chat"
      - ONE_MIN_AVAILABLE_MODELS=mistral-nemo,gpt-4o-mini,deepseek-chat
      # Set your boolean as "True" or "False" for PERMIT_MODELS_NOT_IN_AVAILABLE_MODELS Default: False
      - PERMIT_MODELS_NOT_IN_AVAILABLE_MODELS=True