services:
  # Database
  memcached:
    image: memcached:latest
    networks:
      - 1min-relay-network
    restart: unless-stopped
    # Does not require to expose port. Only used for internal communication.
  # 1min-relay
  1min-relay:
    image: ghcr.io/kokofixcomputers/1min_relay:latest # Pull from GitHub.
    container_name: 1min-relay-container
    ports:
      - "5001:5001"
    networks:
      - 1min-relay-network
    depends_on:
      - memcached
    environment:
      # Use comma-separated string for ONE_MIN_AVAILABLE_MODELS Default: "mistral-nemo", "gpt-4o", "deepseek-chat"
      - SUBSET_OF_ONE_MIN_PERMITTED_MODELS=mistral-nemo,gpt-4o-mini,deepseek-chat
      # Set your boolean as "True" or "False" for PERMIT_MODELS_NOT_IN_AVAILABLE_MODELS Default: False
      - PERMIT_MODELS_FROM_SUBSET_ONLY=True
    restart: unless-stopped

networks:
  1min-relay-network:  # Define the custom network